// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnx8RbhZcFl1STuftx0PlWOdBXdqMCefw',
    appId: '1:31783007813:android:06014948323230d60a152c',
    messagingSenderId: '31783007813',
    projectId: 'hidroponic-reni',
    databaseURL: 'https://hidroponic-reni-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hidroponic-reni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemo9kxaH7Kp9XUq_nNMCmThjSdAKcqZ4',
    appId: '1:31783007813:ios:db7e0cb9eddba7590a152c',
    messagingSenderId: '31783007813',
    projectId: 'hidroponic-reni',
    databaseURL: 'https://hidroponic-reni-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hidroponic-reni.firebasestorage.app',
    iosBundleId: 'com.example.hidroponikApp2',
  );
}
